version: 2

sources:
  - name: raw
    description: Datos de origen cargados por Airflow sin transformaciones de negocio.
    schema: raw
    tables:
      - name: transacciones_raw
        description: Cabecera de transacciones tal como llega al laboratorio.
        columns:
          - name: id_transaccion
            data_tests:
              - not_null
              - unique
      - name: items_transaccion_raw
        description: Detalle de productos tal como llega al laboratorio.
        columns:
          - name: id_item
            data_tests:
              - not_null
              - unique
      - name: cuentas_raw
        columns:
          - name: id_cuenta
            data_tests:
              - not_null
              - unique
      - name: canales_raw
        columns:
          - name: id_canal
            data_tests:
              - not_null
              - unique
      - name: estados_transaccion_raw
        columns:
          - name: id_estado
            data_tests:
              - not_null
              - unique
      - name: productos_raw
        columns:
          - name: id_producto
            data_tests:
              - not_null
              - unique
